name: test

on:
  push:
    branches:
      - "**"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    strategy:
      matrix:
        arch: [ x86_64 ]
      fail-fast: false

    steps:
      - name: Update system
        run: |
          pacman -Syu --noconfirm
          
      - name: Install Git
        run: |
          pacman -Sy
          pacman -S --noconfirm git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Print working directory
        run: pwd

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1.10
        with:
          repository: MaaXYZ/MaaFramework
          latest: true
          fileName: "MAA-linux-${{ matrix.arch }}*"
          out-file-path: "deps"
          extract: true

      - name: Build
        run: |
          export CGO_CFLAGS="-I/__w/maa-framework-go-test/maa-framework-go-test/deps/include"
          export CGO_LDFLAGS="-L/__w/maa-framework-go-test/maa-framework-go-test/deps/bin -lMaaFramework -lMaaToolkit"
          go build -v -tags customenv -o demo

      - name: Run
        run: |
          cp -r TestingDataSet/MaaCommonAssets/OCR/ppocr_v4/zh_cn TestingDataSet/PipelineSmoking/resource/model/ocr
          export LD_LIBRARY_PATH=/__w/maa-framework-go-test/maa-framework-go-test/deps/bin:$LD_LIBRARY_PATH
          ./demo

  macos:
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: aarch64
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Print working directory
        run: pwd

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1.10
        with:
          repository: MaaXYZ/MaaFramework
          latest: true
          fileName: "MAA-macos-${{ matrix.arch }}*"
          out-file-path: "deps"
          extract: true

      - name: Build
        run: |
          export CGO_CFLAGS="-I/Users/runner/work/maa-framework-go-test/maa-framework-go-test/deps/include"
          export CGO_LDFLAGS="-L/Users/runner/work/maa-framework-go-test/maa-framework-go-test/deps/bin -lMaaFramework -lMaaToolkit"
          go build -v -tags customenv -o demo

      - name: Run
        run: |
          mkdir -p TestingDataSet/PipelineSmoking/resource/model/ocr
          cp -r TestingDataSet/MaaCommonAssets/OCR/ppocr_v4/zh_cn TestingDataSet/PipelineSmoking/resource/model/ocr
          export DYLD_LIBRARY_PATH=/Users/runner/work/maa-framework-go-test/maa-framework-go-test/deps/bin:$DYLD_LIBRARY_PATH
          ./demo
          


